#!/usr/bin/env bash
# PreToolUse guard for Edit|Write.
# Denies writes to generated, vendored, or lock-managed files. These are
# produced by a tool (bun, next, skills sync) and hand-edits get silently
# clobbered on the next run.
set -uo pipefail

payload="$(cat)"
file="$(printf '%s' "$payload" | jq -r '.tool_input.file_path // empty')"
[ -z "$file" ] && exit 0

root="${CLAUDE_PROJECT_DIR:-$PWD}"
rel="${file#"$root"/}"

deny() {
  jq -nc --arg reason "$1" '{
    hookSpecificOutput: {
      hookEventName: "PreToolUse",
      permissionDecision: "deny",
      permissionDecisionReason: $reason
    }
  }'
  exit 0
}

case "$rel" in
  bun.lock|package-lock.json|yarn.lock|pnpm-lock.yaml)
    deny "$rel is a lockfile. Change dependencies with 'bun add/remove' and let bun rewrite it." ;;
  next-env.d.ts|tsconfig.tsbuildinfo)
    deny "$rel is generated by Next.js/TypeScript and is gitignored. Edits here do not persist." ;;
  .next/*|node_modules/*|.direnv/*)
    deny "$rel is inside a build/dependency directory. Edit the source that produces it." ;;
  .agents/skills/*)
    deny "$rel is a vendored skill tracked in skills-lock.json. Edit it upstream, or copy it into .claude/skills/ under a new name." ;;
esac

exit 0
